{{- if .Values.replicated.enabled }}
apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: groovelab
spec:
  chart:
    name: groovelab
    chartVersion: {{ .Chart.Version }}
  releaseName: groovelab
  namespace: groovelab
  useHelmInstallOperator: true
  helmUpgradeFlags:
    - --atomic
    - --timeout=300s
  values:
    features:
      trackExport:
        enabled: '{{`{{repl LicenseFieldValue "track_export_enabled"}}`}}'
    cnpg:
      createCluster: '{{`{{repl ConfigOptionEquals "db_type" "embedded"}}`}}'
    externalDatabase:
      host: '{{`{{repl ConfigOption "external_db_host"}}`}}'
      port: '{{`{{repl ConfigOption "external_db_port"}}`}}'
      username: '{{`{{repl ConfigOption "external_db_user"}}`}}'
      password: '{{`{{repl ConfigOption "external_db_password"}}`}}'
      sslMode: '{{`{{repl ConfigOption "external_db_ssl_mode"}}`}}'
    auth:
      sessionDuration: '{{`{{repl ConfigOption "session_duration"}}`}}'
      guestAccess: '{{`{{repl ConfigOptionEquals "guest_access" "1"}}`}}'
    flashcards:
      maxCardsPerSession: '{{`{{repl ConfigOption "max_cards_per_session"}}`}}'
  optionalValues:
    - when: '{{`{{repl ne (LicenseFieldValue "track_export_enabled") ""}}`}}'
      recursiveMerge: true
      values:
        features:
          trackExport:
            enabled: '{{`{{repl LicenseFieldValue "track_export_enabled"}}`}}'
    - when: '{{`{{repl ConfigOptionEquals "db_type" "external"}}`}}'
      recursiveMerge: true
      values:
        cnpg:
          createCluster: "false"
{{- end }}
