---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "groovelab.fullname" . }}-preflight
  labels:
    {{- include "groovelab.labels" . | nindent 4 }}
    troubleshoot.sh/kind: preflight
type: Opaque
stringData:
  preflight.yaml: |
    {{- include "groovelab.preflight.spec" . | nindent 4 }}
