{{- if .Values.cnpg.createCluster }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "groovelab.fullname" . }}-cnpg-credentials
  labels:
    {{- include "groovelab.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.cnpg.owner | default "groovelab" | b64enc | quote }}
  password: {{ .Values.cnpg.password | default (randAlphaNum 20) | b64enc | quote }}
{{- end }}
