{{- if index .Values "cloudnative-pg" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "groovelab.fullname" . }}-cnpg-credentials
  labels:
    {{- include "groovelab.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cnpg.owner | default "groovelab" }}
  password: {{ .Values.cnpg.password | default (randAlphaNum 16) | quote }}
{{- end }}
